### PR TITLE
Merge dev-lew into dev

### PR DESCRIPTION
**Pull request by LRossman**
Merging latest changes made to my forked repository into the USEPA/EPANETMSX dev branch. @fengshang1972 please review to see if you agree with my changes. If you prefer, I can keep dev-lew as a separate branch.

### CODE REVIEW

**Comment by fengshang1972** [comment]
@LRossman 

We got specific request on WQ time step being smaller than 1 second. The following is from Mirjam of KWR water.

-------------------------------------------------------------------------------------------------------------------------------------
Hi Feng,

When modelling the premise plumbing system we need really short water quality time steps, that is 0.1 seconds or even smaller. However, it seems that MSX cannot go below 1 second. Is that correct? 

Best regards,
E.J.M. (Mirjam) Blokker, PhD_

**Comment by LRossman** [comment]
I don't understand why time steps < 1 sec are needed. If reactions are that fast then they should be replaced by equilibrium expressions. As I mentioned to you before, using a double for time steps can cause problems when using an equality test to check if the next hydraulic or reporting time step has been reached (you might miss catching a change in hydraulics because the floating point elapsed time will not exactly equal a whole number of seconds). One solution is to use 64-bit integers (int64_t) to represent time in milliseconds. Should I modify the code to do so?

**Comment by fengshang1972** [comment]
Lew, representing time in millisecond is a great solution. 

Since the MSX.Htime is the next hydraulic event time, can we change the == to >= to avoid the missing of hydraulic changes or reporting time? That can be a quick fix.

if (MSX.Qtime >= 1.0*MSX.Htime)
...
if (MSX.Saveflag && MSX.Qtime >= 1.0*MSX.Rtime)

**Comment by LRossman** [comment]
The latest commit adds support for the MSX time step input as a floating point number of seconds which is converted internally to a 64-bit integer number of milliseconds. This makes for an exact determination of when a new hydraulic solution or a saving of results occurs. The arguments to the MSXstep function (`t `and `tleft` in seconds) remain as doubles.

The code was also cleaned up by eliminating superfluous tabs and blank lines.

**Pull request merged**
